name: Mirror to HMI repo

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read # repo contents are read (push uses PAT secret with its own scopes)
  actions: read

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Push to evschneider-hmi/ps-html5auditor
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.HMI_PAT }} # Fine-grained PAT in source repo secrets
          repository: evschneider-hmi/ps-html5auditor
          branch: main
          force: true
