name: Mirror to HMI repo

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read # repo contents are read (push uses PAT secret with its own scopes)
  actions: read

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Validate PAT secret
        run: |
          if [ -z "${{ secrets.HMI_PAT }}" ]; then
            echo "HMI_PAT secret is not defined in source repo settings (Settings > Secrets and variables > Actions)." >&2
            exit 1
          fi
          echo "HMI_PAT secret is present (length: ${#HMI_PAT}). Proceeding." | sed 's/./*/g'
      - name: Push to evschneider-hmi/ps-html5auditor
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.HMI_PAT }} # Fine-grained PAT in source repo secrets
          repository: evschneider-hmi/ps-html5auditor
          branch: main
          force: true
      - name: Fallback manual push (only runs if previous step failed)
        if: failure()
        run: |
          set -e
          echo "Attempting manual fallback push using PAT..."
          git remote add mirror https://x-access-token:${{ secrets.HMI_PAT }}@github.com/evschneider-hmi/ps-html5auditor.git
          git push mirror HEAD:main --force
          echo "Manual push completed."
