name: Mirror to HMI repo

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read # repo contents are read (push uses PAT secret with its own scopes)
  actions: read

jobs:
  mirror:
    runs-on: ubuntu-latest
    env:
      HMI_PAT: ${{ secrets.HMI_PAT }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Validate PAT secret
        run: |
          if [ -z "$HMI_PAT" ]; then
            echo "HMI_PAT secret is not defined in source repo settings (Settings > Secrets and variables > Actions)." >&2
            exit 1
          fi
          echo "HMI_PAT secret detected (length: ${#HMI_PAT}). Proceeding without revealing value." 
          if [ ${#HMI_PAT} -lt 30 ]; then
            echo "Warning: PAT length seems short (<30). Ensure you used the full token when saving the secret." >&2
          fi
      - name: Test remote access with PAT
        run: |
          set -e
          echo "Testing remote access to target repo..."
          if git ls-remote "https://x-access-token:$HMI_PAT@github.com/evschneider-hmi/ps-html5auditor.git" HEAD > /dev/null 2>&1; then
            echo "Remote access OK."
          else
            echo "Failed to access target repo with supplied PAT. Common causes:" >&2
            echo " - PAT not granted repository access (fine-grained: add ps-html5auditor)" >&2
            echo " - Missing 'Contents: Read and Write' permission" >&2
            echo " - Organization/repo requires SSO authorization (authorize the token)" >&2
            exit 2
          fi
      - name: Force push mirror
        run: |
          set -e
          git config user.name "mirror-bot"
          git config user.email "mirror-bot@users.noreply.github.com"
          # Add/replace mirror remote
          if git remote | grep -q '^mirror$'; then
            git remote remove mirror
          fi
            
          git remote add mirror "https://x-access-token:$HMI_PAT@github.com/evschneider-hmi/ps-html5auditor.git"
          echo "Pushing to target (force)..."
          git push mirror HEAD:main --force
          echo "Mirror push complete."
